---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance1
    image: mmumshad/ubuntu-ssh-enabled
  - name: instance2
    image: mmumshad/ubuntu-ssh-enabled
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  # lint:
  #   name: flake8
